Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox"
  config.vm.box = "relativkreativ/centos-7-minimal"
  config.vm.synced_folder "~/gocode", "/srv/gocode"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network "public_network", bridge: 'en0: Wi-Fi (AirPort)'
  config.vm.network "forwarded_port", guest: 80, host: 8008
end
